import addSharp from '../../assets/icons/add-sharp.svg';
import { useWindowSize } from '../../hooks/useWindowSize';
import { aboutImages } from '../../utils/aboutScrSet';
import s from './about.module.scss';

export const About = () => {
  const { width } = useWindowSize();

  let srcSetAbout = {};
  if (width < 768) {
    srcSetAbout = {
      src: aboutImages.aboutMobil1X,
      srcSet: `${aboutImages.aboutMobil1X} 1x, ${aboutImages.aboutMobil2X} 2x`,
    };
  } else if (width >= 768 && width < 1280) {
    srcSetAbout = {
      src: aboutImages.aboutTablet1X,
      srcSet: `${aboutImages.aboutTablet1X} 1x, ${aboutImages.aboutTablet2X} 2x`,
    };
  } else {
    srcSetAbout = {
      src: aboutImages.aboutDesktop1X,
      srcSet: `${aboutImages.aboutDesktop1X} 1x, ${aboutImages.aboutDesktop2X} 2x`,
    };
  }

  return (
    <section className={s.section}>
      <div className={s.container}>
        <div className={s.wrapTitle}>
          <h2 className={s.title}>
            a Story  that started with
            <span>
              &nbsp;one simple <br /> ape
            </span>
          </h2>
          <p className={s.dynamicJourney}>
            WHO GOT FED UP WITH BORING AND HYPOCRITIC COMMONPLACE THIS IS HOW
            THE IDEA OF ESCAPING AND DYNAMIC JOURNEY ON THE <br /> YACHT
          </p>
        </div>
        <div className={s.wrapStory}>
          <img src={addSharp} alt="cross" className={s.croos} />
          <p className={s.storyTelling}>
            EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY. ARTS
            ARE RANDOMLY GENERATED BY USERS
          </p>
        </div>
        <img
          className={s.imgHero}
          src={srcSetAbout.src}
          srcSet={srcSetAbout.srcSet}
          alt="hero"
        />
      </div>
    </section>
  );
};
